[tox]
envlist = py312, lint
skipsdist = false

[testenv]
extras = dev
commands =
    pytest {posargs:tests/}

[testenv:lint]
deps =
    ruff
commands =
    ruff check udp_client/ tests/ main.py config.py
    ruff format --check udp_client/ tests/ main.py config.py
